theme = "catppuccin_mocha"

[editor]
color-modes = true
line-number = "relative"
true-color = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-j = "save_selection"
C-c = "no_op"
C-n = ["move_prev_word_start", "move_next_word_end", "search_selection", "extend_search_next"]
"esc" = ["collapse_selection", "keep_primary_selection"]
# L = ["select_mode", "goto_line_end", "normal_mode"]
L = ["goto_line_end", "normal_mode"]
# H = ["select_mode", "goto_line_start", "normal_mode"]
H = ["goto_line_start", "normal_mode"]
V = ["select_mode", "extend_to_line_bounds"]
X = "extend_line_above"
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]

[keys.select]
C-c = "no_op"
C-n = ["search_selection", "extend_search_next"]
L = ["goto_line_end"]
H = ["goto_line_start"]
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
