theme = "catppuccin_mocha"

[editor]
line-number = "relative"
color-modes = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-j = "save_selection"
# C-c = "no_op"
"esc" = ["collapse_selection", "keep_primary_selection"]
L = ["select_mode", "goto_line_end", "normal_mode"]
H = ["select_mode", "goto_line_start", "normal_mode"]
V = ["select_mode", "extend_to_line_bounds"]
X = "extend_line_above"

[keys.normal.space]
c = "toggle_comments"

# [keys.select]
# C-c = "no_op"

[keys.select.space]
c = "toggle_comments"
